apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app.kubernetes.io/instance: relayer-testnet
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: '8080'
  selector:
    app.kubernetes.io/name: explorer
