apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  labels:
    app.kubernetes.io/instance: starship-generator-test
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: starship
data:
  core-1.json: '{"chain_name":"persistencecore","assets":[]}'
