apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    starship.io/name: xpla
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: registry
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: registry
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
