apiVersion: v1
kind: ConfigMap
metadata:
  name: go-relayer-go-relay
  labels:
    app.kubernetes.io/instance: relayer-testnet
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: relayer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/role: go-relayer
    app.kubernetes.io/name: go-relayer-go-relay
data:
  path.json: |-
    {
      "src": {
        "chain-id": "osmosis-1"
      },
      "dst": {
        "chain-id": "cosmoshub-4"
      },
      "src-channel-filter": {
        "rule": null,
        "channel-list": []
      }
    }
  osmosis-1.json: |-
    {
      "type": "cosmos",
      "value": {
        "key": "default",
        "chain-id": "osmosis-1",
        "rpc-addr": "http://osmosis-1-genesis.$(NAMESPACE).svc.cluster.local:26657",
        "account-prefix": "osmo",
        "keyring-backend": "test",
        "gas-adjustment": 1.5,
        "gas-prices": "0.025uosmo",
        "min-gas-amount": 1,
        "debug": true,
        "timeout": "20s",
        "output-format": "json",
        "sign-mode": "direct"
      }
    }
  cosmoshub-4.json: |-
    {
      "type": "cosmos",
      "value": {
        "key": "default",
        "chain-id": "cosmoshub-4",
        "rpc-addr": "http://cosmoshub-4-genesis.$(NAMESPACE).svc.cluster.local:26657",
        "account-prefix": "cosmos",
        "keyring-backend": "test",
        "gas-adjustment": 1.5,
        "gas-prices": "0.025uatom",
        "min-gas-amount": 1,
        "debug": true,
        "timeout": "20s",
        "output-format": "json",
        "sign-mode": "direct"
      }
    }
