name: starship-e2e-tests
version: 1.7.0

chains:
  - id: 1337
    name: ethereum
    image: ghcr.io/hyperweb-io/starship/ethereum/client-go:v1.14.12
    numValidators: 1
    ports:
      rest: 8545
      rpc: 8551
      ws: 8546
    resources:
      cpu: "200m"
      memory: "200Mi"
    balances:
      - address: "0x0000000000000000000000000000000000000002"
        amount: "0x3635c9adc5dea00000"
