name: starship-e2e-tests-full-stack
version: 1.7.0

chains:
  - id: osmosis-1
    name: osmosis
    numValidators: 2
    metrics: true
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1313
      rpc: 26653
      exposer: 38083
      faucet: 8001
    resources:
      cpu: "1"
      memory: "2Gi"
  - id: cosmoshub-4
    name: cosmoshub
    image: ghcr.io/cosmology-tech/starship/gaia:v10.0.1
    numValidators: 2
    metrics: true
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      faucet: 8007
    resources:
      cpu: "1"
      memory: "2Gi"

relayers:
  - name: osmos-cosmos
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmoshub-4
    config:
      telemetry:
        enabled: true
    resources:
      cpu: "0.5"
      memory: "1Gi"

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
  resources:
    cpu: "0.2"
    memory: "200M"

explorer:
  enabled: true
  type: ping-pub
  ports:
    rest: 8080
  resources:
    cpu: "1"
    memory: "2Gi"

frontends:
  - name: web-app
    image: nginx:latest
    ports:
      http: 3000
    resources:
      cpu: "0.5"
      memory: "1Gi"

monitoring:
  enabled: true
  ports:
    grafana: 8082
    prometheus: 8083
  resources:
    cpu: "0.5"
    memory: "1Gi"

ingress:
  enabled: true
  type: nginx
  host: "*.starship-test.io"
  certManager:
    issuer: "letsencrypt-prod" 