{
 "title": "Chain Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values({__name__=~\"^(tendermint|cometbft)_consensus_latest_block_height\",network=~\".*\"},network)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{network=\"$network\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tendermint Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Number of Validators",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (network,instance) ({__name__=~\"^(tendermint|cometbft)_consensus_missing_validators\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "missing validators"
    },
    {
     "expr": "avg by (network) ({__name__=~\"^(tendermint|cometbft)_consensus_validators\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "total validators"
    },
    {
     "expr": "avg by (network) ({__name__=~\"^(tendermint|cometbft)_consensus_missing_validators$\",network=\"$network\",instance=\"$instance\"}) / avg by (network) ({__name__=~\"^(tendermint|cometbft)_consensus_validators$\",network=\"$network\",instance=\"$instance\"}) * 100",
     "legendFormat": "missing %"
    }
   ]
  },
  {
   "title": "Voting power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (network,instance) ({__name__=~\"^(tendermint|cometbft)_consensus_validators_power\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (network,instance) ({__name__=~\"^(tendermint|cometbft)_consensus_missing_validators_power\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "Missing"
    },
    {
     "expr": "max by (network,instance) ({__name__=~\"^(tendermint|cometbft)_consensus_missing_validators_power$\",network=\"$network\",instance=\"$instance\"}) / max by (network,instance) ({__name__=~\"^(tendermint|cometbft)_consensus_validators_power$\",network=\"$network\",instance=\"$instance\"}) * 100",
     "legendFormat": "Missing %"
    }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by (instance) ({__name__=~\"^(tendermint|cometbft)_consensus_latest_block_height\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max by (network) ({__name__=~\"^(tendermint|cometbft)_consensus_validator_last_signed_height\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "Validator last signed"
    }
   ]
  },
  {
   "title": "P2P connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"^(tendermint|cometbft)_p2p_peers\",network=\"$network\",instance=\"$instance\"}",
     "legendFormat": "peers {{instance}}"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (network) (1/rate({__name__=~\"^(tendermint|cometbft)_consensus_height\",network=\"$network\",instance=\"$instance\"}[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "avg by (network) (1/rate({__name__=~\"^(tendermint|cometbft)_consensus_height\",network=\"$network\",instance=\"$instance\"}[1h]))",
     "legendFormat": "1h"
    },
    {
     "expr": "avg by (network) (1/rate({__name__=~\"^(tendermint|cometbft)_consensus_height\",network=\"$network\",instance=\"$instance\"}[1d]))",
     "legendFormat": "1d"
    }
   ]
  },
  {
   "title": "Validator Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (network) ({__name__=~\"^(tendermint|cometbft)_consensus_validator_missed_blocks\",network=\"$network\",instance=\"$instance\"})",
     "legendFormat": "total"
    },
    {
     "expr": "max by (network) (delta({__name__=~\"^(tendermint|cometbft)_consensus_validator_missed_blocks\",network=\"$network\",instance=\"$instance\"}[1h]))",
     "legendFormat": "1h"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"^(tendermint|cometbft)_mempool_size\",network=\"$network\",instance=\"$instance\"}",
     "legendFormat": "{{instance}} - Total Txs"
    },
    {
     "expr": "rate({__name__=~\"^(tendermint|cometbft)_mempool_tx_size_bytes_sum\",network=\"$network\",instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}} - Tx Size Inflow (1min)"
    }
   ]
  },
  {
   "title": "Finalized Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_total_txs\",network=\"$network\",instance=\"$instance\"}[1m])",
     "legendFormat": "Confirmed (1min)"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_mempool_failed_txs\",network=\"$network\",instance=\"$instance\"}[1m])",
     "legendFormat": "Failed (1min)"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_mempool_failed_txs$\",network=\"$network\",instance=\"$instance\"}[1m]) / (increase({__name__=~\"^(tendermint|cometbft)_mempool_failed_txs$\",network=\"$network\",instance=\"$instance\"}[1m]) + increase({__name__=~\"^(tendermint|cometbft)_consensus_total_txs$\",network=\"$network\",instance=\"$instance\"}[1m])) * 100",
     "legendFormat": "Total % (1min)"
    }
   ]
  },
  {
   "title": "Block Parts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_block_gossip_parts_received\",network=\"$network\",matches_current=\"true\",instance=\"$instance\"}[1m])",
     "legendFormat": "Parts Received - Matching current (1m)"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_block_gossip_parts_received\",network=\"$network\",matches_current=\"false\",instance=\"$instance\"}[1m])",
     "legendFormat": "Parts Received - Not matching (1m)"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"^(tendermint|cometbft)_consensus_block_size_bytes\",network=\"$network\",instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"^(tendermint|cometbft)_consensus_rounds\",network=\"$network\",instance=\"$instance\"}",
     "legendFormat": "Consensus Rounds"
    }
   ]
  },
  {
   "title": "Step duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_step_duration_seconds_sum\",network=\"$network\",step=\"Prevote\",instance=\"$instance\"}[1m]) / 100",
     "legendFormat": "Prevote"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_step_duration_seconds_sum\",network=\"$network\",step=\"Precommit\",instance=\"$instance\"}[1m]) / 100",
     "legendFormat": "Precommit"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_step_duration_seconds_sum\",network=\"$network\",step=\"Commit\",instance=\"$instance\"}[1m]) / 100",
     "legendFormat": "Commit"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_step_duration_seconds_sum\",network=\"$network\",step=\"NewHeight\",instance=\"$instance\"}[1m]) / 100",
     "legendFormat": "New Height"
    },
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_consensus_step_duration_seconds_sum\",network=\"$network\",step=\"Propose\",instance=\"$instance\"}[1m]) / 100",
     "legendFormat": "Propose"
    }
   ]
  },
  {
   "title": "Bytes received / s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_p2p_message_receive_bytes_total\",network=\"$network\",instance=\"$instance\"}[1m]) / 600",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Bytes sent / s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_p2p_message_send_bytes_total\",network=\"$network\",instance=\"$instance\"}[1m])/600",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Bytes received (1d)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_p2p_message_receive_bytes_total\",network=\"$network\",instance=\"$instance\"}[1d])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Bytes sent (1d)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"^(tendermint|cometbft)_p2p_message_send_bytes_total\",network=\"$network\",instance=\"$instance\"}[1d])",
     "legendFormat": "{{message_type}}"
    }
   ]
  }
 ]
}