apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-neutron-cosmos
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: relayer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/role: hermes
    app.kubernetes.io/name: hermes-neutron-cosmos
data:
  config.toml: |
    # The global section has parameters that apply globally to the relayer operation.
    [global]
    log_level = "info"

    [mode]
    [mode.clients]
    enabled = true
    refresh = true
    misbehaviour = true

    [mode.connections]
    enabled = true

    [mode.channels]
    enabled = true

    [mode.packets]
    enabled = true
    clear_interval = 100
    clear_on_start = true
    tx_confirmation = true

    [rest]
    enabled = true
    host = "0.0.0.0"
    port = 3000

    [telemetry]
    enabled = true
    host = "0.0.0.0"
    port = 3001


    [[chains]]
    id = "neutron-1"
    type = "CosmosSdk"
    key_name = "neutron-1"
    ccv_consumer_chain = true
    rpc_addr = "http://neutron-1-genesis.$NAMESPACE.svc.cluster.local:26657"
    grpc_addr = "http://neutron-1-genesis.$NAMESPACE.svc.cluster.local:9090"
    event_source = { mode = 'push', url = "ws://neutron-1-genesis.$NAMESPACE.svc.cluster.local:26657/websocket", batch_delay = '500ms' }
    trusted_node = false
    account_prefix = "neutron"
    default_gas = 500000000
    max_gas = 1000000000
    rpc_timeout = "10s"
    store_prefix = "ibc"
    gas_multiplier = 2
    max_msg_num = 30
    max_tx_size = 2097152
    clock_drift = "5s"
    max_block_time = "30s"
    trusting_period = "75s"
    trust_threshold = { numerator = "2", denominator = "3" }
    address_type = { derivation = 'cosmos' }
    gas_price = { price = 1.25, denom = "untrn" }

    [[chains]]
    id = "cosmoshub-4"
    type = "CosmosSdk"
    key_name = "cosmoshub-4"

    rpc_addr = "http://cosmoshub-4-genesis.$NAMESPACE.svc.cluster.local:26657"
    grpc_addr = "http://cosmoshub-4-genesis.$NAMESPACE.svc.cluster.local:9090"
    event_source = { mode = 'push', url = "ws://cosmoshub-4-genesis.$NAMESPACE.svc.cluster.local:26657/websocket", batch_delay = '500ms' }
    trusted_node = false
    account_prefix = "cosmos"
    default_gas = 500000000
    max_gas = 1000000000
    rpc_timeout = "10s"
    store_prefix = "ibc"
    gas_multiplier = 2
    max_msg_num = 30
    max_tx_size = 2097152
    clock_drift = "5s"
    max_block_time = "30s"
    trusting_period = "75s"
    trust_threshold = { numerator = "2", denominator = "3" }
    address_type = { derivation = 'cosmos' }
    gas_price = { price = 1.25, denom = "uatom" }
  config-cli.toml: |
    # The global section has parameters that apply globally to the relayer operation.
    [global]
    log_level = "info"

    [mode]
    [mode.clients]
    enabled = true
    refresh = true
    misbehaviour = true

    [mode.connections]
    enabled = true

    [mode.channels]
    enabled = true

    [mode.packets]
    enabled = true
    clear_interval = 100
    clear_on_start = true
    tx_confirmation = true

    [rest]
    enabled = true
    host = "0.0.0.0"
    port = 3000

    [telemetry]
    enabled = true
    host = "0.0.0.0"
    port = 3001


    [[chains]]
    id = "neutron-1"
    type = "CosmosSdk"
    key_name = "neutron-1-cli"
    ccv_consumer_chain = true
    rpc_addr = "http://neutron-1-genesis.$NAMESPACE.svc.cluster.local:26657"
    grpc_addr = "http://neutron-1-genesis.$NAMESPACE.svc.cluster.local:9090"
    event_source = { mode = 'push', url = "ws://neutron-1-genesis.$NAMESPACE.svc.cluster.local:26657/websocket", batch_delay = '500ms' }
    trusted_node = false
    account_prefix = "neutron"
    default_gas = 500000000
    max_gas = 1000000000
    rpc_timeout = "10s"
    store_prefix = "ibc"
    gas_multiplier = 2
    max_msg_num = 30
    max_tx_size = 2097152
    clock_drift = "5s"
    max_block_time = "30s"
    trusting_period = "75s"
    trust_threshold = { numerator = "2", denominator = "3" }
    address_type = { derivation = 'cosmos' }
    gas_price = { price = 1.25, denom = "untrn" }

    [[chains]]
    id = "cosmoshub-4"
    type = "CosmosSdk"
    key_name = "cosmoshub-4-cli"

    rpc_addr = "http://cosmoshub-4-genesis.$NAMESPACE.svc.cluster.local:26657"
    grpc_addr = "http://cosmoshub-4-genesis.$NAMESPACE.svc.cluster.local:9090"
    event_source = { mode = 'push', url = "ws://cosmoshub-4-genesis.$NAMESPACE.svc.cluster.local:26657/websocket", batch_delay = '500ms' }
    trusted_node = false
    account_prefix = "cosmos"
    default_gas = 500000000
    max_gas = 1000000000
    rpc_timeout = "10s"
    store_prefix = "ibc"
    gas_multiplier = 2
    max_msg_num = 30
    max_tx_size = 2097152
    clock_drift = "5s"
    max_block_time = "30s"
    trusting_period = "75s"
    trust_threshold = { numerator = "2", denominator = "3" }
    address_type = { derivation = 'cosmos' }
    gas_price = { price = 1.25, denom = "uatom" }
