apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer
  labels:
    app.kubernetes.io/instance: starship-generator-test
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
data:
  1337.json: >-
    {"chain_name":1337,"coingecko":"ethereum","api":"http://1337-genesis.$(NAMESPACE).svc.cluster.local:8545","rpc":["http://1337-genesis.$(NAMESPACE).svc.cluster.local:8551"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":60,"min_tx_fee":"3000","addr_prefix":"eth","logo":"","assets":[{"base":"wei","symbol":"ETH","exponent":"6","coingecko_id":1337,"logo":""}]}
