apiVersion: v1
kind: Service
metadata:
  name: hermes-osmosis-juno
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: relayer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/role: hermes
    app.kubernetes.io/name: hermes-osmosis-juno
spec:
  clusterIP: None
  ports:
    - name: rest
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: exposer
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: hermes-osmosis-juno
