apiVersion: v1
kind: ConfigMap
metadata:
  name: patch-osmosis-build
  labels:
    app.kubernetes.io/instance: complex-testnet
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: chain
    app.kubernetes.io/name: osmosis
    app.kubernetes.io/part-of: osmosis-build
    app.kubernetes.io/role: genesis-patch
data:
  patch.json: |-
    {
      "app_state": {
        "staking": {
          "params": {
            "unbonding_time": "5s"
          }
        },
        "gamm": {
          "params": {
            "pool_creation_fee": [
              {
                "amount": "500000",
                "denom": "uosmo"
              }
            ]
          }
        }
      }
    }
