apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osmosis-genesis
  labels:
    app.kubernetes.io/instance: complex-testnet
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/id: osmosis-cosmjs
    app.kubernetes.io/name: osmosis-genesis
    app.kubernetes.io/type: osmosis-cosmjs-statefulset
spec:
  serviceName: osmosis-genesis
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: osmosis
      app.kubernetes.io/name: osmosis-cosmjs-genesis
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: osmosis
        app.kubernetes.io/type: osmosis-cosmjs
        app.kubernetes.io/name: osmosis-cosmjs-genesis
        app.kubernetes.io/rawname: osmosis-cosmjs
        app.kubernetes.io/version: 1.8.0
    spec:
      initContainers:
        - name: init-genesis
          image: ghcr.io/cosmology-tech/starship/osmosis:v25.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DENOM
              value: uosmo
            - name: COINS
              value: 100000000000000uosmo,100000000000000uion
            - name: CHAIN_BIN
              value: osmosisd
            - name: CHAIN_DIR
              value: /root/.osmosisd
            - name: CODE_REPO
              value: https://github.com/osmosis-labs/osmosis
            - name: DAEMON_HOME
              value: /root/.osmosisd
            - name: DAEMON_NAME
              value: osmosisd
            - name: CHAIN_ID
              value: osmosis-cosmjs
            - name: KEYS_CONFIG
              value: /configs/keys.json
            - name: FAUCET_ENABLED
              value: 'true'
            - name: NUM_VALIDATORS
              value: '1'
            - name: NUM_RELAYERS
              value: '0'
          command:
            - bash
            - '-c'
            - /scripts/create-genesis.sh
          resources:
            limits:
              cpu: '0.5'
              memory: 500M
            requests:
              cpu: '0.5'
              memory: 500M
          volumeMounts:
            - mountPath: /root/.osmosisd
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
        - name: init-config
          image: ghcr.io/cosmology-tech/starship/osmosis:v25.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DENOM
              value: uosmo
            - name: COINS
              value: 100000000000000uosmo,100000000000000uion
            - name: CHAIN_BIN
              value: osmosisd
            - name: CHAIN_DIR
              value: /root/.osmosisd
            - name: CODE_REPO
              value: https://github.com/osmosis-labs/osmosis
            - name: DAEMON_HOME
              value: /root/.osmosisd
            - name: DAEMON_NAME
              value: osmosisd
            - name: CHAIN_ID
              value: osmosis-cosmjs
            - name: KEYS_CONFIG
              value: /configs/keys.json
            - name: METRICS
              value: 'false'
          command:
            - bash
            - '-c'
            - /scripts/update-config.sh
          resources:
            limits:
              cpu: '0.5'
              memory: 500M
            requests:
              cpu: '0.5'
              memory: 500M
          volumeMounts:
            - mountPath: /root/.osmosisd
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
      containers:
        - name: validator
          image: ghcr.io/cosmology-tech/starship/osmosis:v25.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DENOM
              value: uosmo
            - name: COINS
              value: 100000000000000uosmo,100000000000000uion
            - name: CHAIN_BIN
              value: osmosisd
            - name: CHAIN_DIR
              value: /root/.osmosisd
            - name: CODE_REPO
              value: https://github.com/osmosis-labs/osmosis
            - name: DAEMON_HOME
              value: /root/.osmosisd
            - name: DAEMON_NAME
              value: osmosisd
            - name: CHAIN_ID
              value: osmosis-cosmjs
            - name: FAUCET_ENABLED
              value: 'true'
            - name: SLOGFILE
              value: slog.slog
          command:
            - bash
            - '-c'
            - |-
              #!/bin/bash
              set -euo pipefail

              echo "Starting osmosisd validator..."
              exec osmosisd start --home /root/.osmosisd --log_level info
          resources:
            limits:
              cpu: '0.5'
              memory: 500M
            requests:
              cpu: '0.5'
              memory: 500M
          volumeMounts:
            - mountPath: /root/.osmosisd
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
          readinessProbe:
            exec:
              command:
                - bash
                - '-e'
                - /scripts/chain-rpc-ready.sh
                - http://localhost:26657
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
        - name: exposer
          image: ghcr.io/cosmology-tech/starship/exposer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GENESIS_HOST
              value: osmosis-cosmjs-genesis
            - name: GENESIS_PORT
              value: '8081'
            - name: NAMESPACE
              value:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            - name: EXPOSER_HTTP_PORT
              value: '8081'
            - name: EXPOSER_GRPC_PORT
              value: '9099'
            - name: EXPOSER_GENESIS_FILE
              value: /root/.osmosisd/config/genesis.json
            - name: EXPOSER_MNEMONIC_FILE
              value: /configs/keys.json
            - name: EXPOSER_PRIV_VAL_FILE
              value: /root/.osmosisd/config/priv_validator_key.json
            - name: EXPOSER_NODE_KEY_FILE
              value: /root/.osmosisd/config/node_key.json
            - name: EXPOSER_NODE_ID_FILE
              value: /root/.osmosisd/config/node_id.json
            - name: EXPOSER_PRIV_VAL_STATE_FILE
              value: /root/.osmosisd/data/priv_validator_state.json
          command:
            - exposer
          resources:
            limits:
              cpu: '0.1'
              memory: 128M
            requests:
              cpu: '0.1'
              memory: 128M
          volumeMounts:
            - mountPath: /root/.osmosisd
              name: node
            - mountPath: /configs
              name: addresses
        - name: faucet
          image: ghcr.io/hyperweb-io/starship/faucet:20250325-2207109
          imagePullPolicy: IfNotPresent
          env:
            - name: FAUCET_CONCURRENCY
              value: '2'
            - name: FAUCET_PORT
              value: '8000'
            - name: FAUCET_GAS_PRICE
              value: '0.025'
            - name: FAUCET_PATH_PATTERN
              value: ''
            - name: FAUCET_ADDRESS_PREFIX
              value: osmo
            - name: FAUCET_TOKENS
              value: uosmo
            - name: FAUCET_CREDIT_AMOUNT_SEND
              value: '10000000'
            - name: FAUCET_CREDIT_AMOUNT_STAKE
              value: '10000000'
            - name: FAUCET_MAX_CREDIT
              value: '99999999'
            - name: FAUCET_MNEMONIC
              value: ''
            - name: FAUCET_CHAIN_ID
              value: osmosis-cosmjs
            - name: FAUCET_RPC_ENDPOINT
              value: http://localhost:26657
          command:
            - yarn
            - start
          resources:
            limits:
              cpu: '0.2'
              memory: 200M
            requests:
              cpu: '0.2'
              memory: 200M
          volumeMounts:
            - mountPath: /configs
              name: addresses
      volumes:
        - name: node
          emptyDir: {}
        - name: addresses
          configMap:
            name: keys
        - name: scripts
          configMap:
            name: setup-scripts-osmosis-cosmjs
