apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: grafana
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: grafana
