apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
  labels:
    starship.io/name: starship-e2e-tests-full-stack
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: explorer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: explorer
      app.kubernetes.io/name: explorer
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: explorer
        app.kubernetes.io/type: ping-pub
        app.kubernetes.io/name: explorer
        app.kubernetes.io/rawname: explorer
        app.kubernetes.io/version: 4.0.0-alpha.0
    spec:
      containers:
        - name: explorer
          image: >-
            ghcr.io/cosmology-tech/starship/ping-pub:6b7b0d096946b6bcd75d15350c7345da0d4576db
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINS_CONFIG_PATH
              value: /explorer
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: explorer-config
              mountPath: /explorer
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
      volumes:
        - name: explorer-config
          configMap:
            name: explorer
