apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: core-1-genesis
  labels:
    starship.io/name: starship-generator-test
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: chain
    app.kubernetes.io/part-of: core-1
    app.kubernetes.io/id: core-1
    app.kubernetes.io/name: core-1-genesis
    app.kubernetes.io/type: core-1-statefulset
    app.kubernetes.io/role: genesis
    starship.io/chain-name: persistencecore
spec:
  serviceName: core-1-genesis
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: starship-generator-test
      app.kubernetes.io/name: core-1-genesis
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: starship-generator-test
        app.kubernetes.io/type: core-1
        app.kubernetes.io/name: core-1-genesis
        app.kubernetes.io/rawname: core-1
        app.kubernetes.io/version: 4.0.0-alpha.0
        app.kubernetes.io/role: genesis
    spec:
      initContainers:
        - name: init-build-images
          image: ghcr.io/cosmology-tech/starship/builder:latest
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - '-c'
            - |-
              # Install cosmovisor
              go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@v1.0.0

              # Build genesis
              UPGRADE_NAME=genesis CODE_TAG=v7.0.0 bash -e /scripts/build-chain.sh
          env:
            - name: CODE_REF
              value: https://github.com/persistenceOne/persistenceCore
            - name: UPGRADE_DIR
              value: /root/.persistenceCore/cosmovisor
            - name: GOBIN
              value: /go/bin
            - name: CHAIN_NAME
              value: core-1
            - name: DENOM
              value: uxprt
            - name: COINS
              value: 100000000000000uxprt
            - name: CHAIN_BIN
              value: persistenceCore
            - name: CHAIN_DIR
              value: /root/.persistenceCore
            - name: CODE_REPO
              value: https://github.com/persistenceOne/persistenceCore
            - name: DAEMON_HOME
              value: /root/.persistenceCore
            - name: DAEMON_NAME
              value: persistenceCore
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - mountPath: /root/.persistenceCore
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
        - name: init-genesis
          image: ghcr.io/cosmology-tech/starship/runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DENOM
              value: uxprt
            - name: COINS
              value: 100000000000000uxprt
            - name: CHAIN_BIN
              value: persistenceCore
            - name: CHAIN_DIR
              value: /root/.persistenceCore
            - name: CODE_REPO
              value: https://github.com/persistenceOne/persistenceCore
            - name: DAEMON_HOME
              value: /root/.persistenceCore
            - name: DAEMON_NAME
              value: persistenceCore
            - name: CHAIN_ID
              value: core-1
            - name: TIME_IOTA_MS
              value: '10'
            - name: TIMEOUT_PROPOSE
              value: 400ms
            - name: TIMEOUT_PROPOSE_DELTA
              value: 400ms
            - name: TIMEOUT_PREVOTE
              value: 400ms
            - name: TIMEOUT_PREVOTE_DELTA
              value: 400ms
            - name: TIMEOUT_PRECOMMIT
              value: 400ms
            - name: TIMEOUT_PRECOMMIT_DELTA
              value: 400ms
            - name: TIMEOUT_COMMIT
              value: 800ms
            - name: KEYS_CONFIG
              value: /configs/keys.json
            - name: FAUCET_ENABLED
              value: 'true'
            - name: NUM_VALIDATORS
              value: '2'
            - name: NUM_RELAYERS
              value: '0'
          command:
            - bash
            - '-c'
            - |-
              VAL_INDEX=${HOSTNAME##*-}
              echo "Validator Index: $VAL_INDEX"

              cp $CHAIN_DIR/cosmovisor/genesis/bin/$CHAIN_BIN /usr/bin

              if [ -f $CHAIN_DIR/config/genesis.json ]; then
                echo "Genesis file exists, exiting init container"
                exit 0
              fi

              echo "Running setup genesis script..."
              bash -e /scripts/create-genesis.sh
              bash -e /scripts/update-genesis.sh

              echo "Create node id json file"
              NODE_ID=$($CHAIN_BIN tendermint show-node-id)
              echo '{"node_id":"'$NODE_ID'"}' > $CHAIN_DIR/config/node_id.json

              echo "Create consensus key json file"
              $CHAIN_BIN tendermint show-validator > $CHAIN_DIR/config/consensus_key.json
              cat $CHAIN_DIR/config/consensus_key.json

              echo "Add custom accounts and balances"
              CHAIN_GENESIS_CMD=$($CHAIN_BIN 2>&1 | grep -q "genesis-related subcommands" && echo "genesis" || echo "")
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - mountPath: /root/.persistenceCore
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
        - name: init-config
          image: ghcr.io/cosmology-tech/starship/runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DENOM
              value: uxprt
            - name: COINS
              value: 100000000000000uxprt
            - name: CHAIN_BIN
              value: persistenceCore
            - name: CHAIN_DIR
              value: /root/.persistenceCore
            - name: CODE_REPO
              value: https://github.com/persistenceOne/persistenceCore
            - name: DAEMON_HOME
              value: /root/.persistenceCore
            - name: DAEMON_NAME
              value: persistenceCore
            - name: CHAIN_ID
              value: core-1
            - name: TIME_IOTA_MS
              value: '10'
            - name: TIMEOUT_PROPOSE
              value: 400ms
            - name: TIMEOUT_PROPOSE_DELTA
              value: 400ms
            - name: TIMEOUT_PREVOTE
              value: 400ms
            - name: TIMEOUT_PREVOTE_DELTA
              value: 400ms
            - name: TIMEOUT_PRECOMMIT
              value: 400ms
            - name: TIMEOUT_PRECOMMIT_DELTA
              value: 400ms
            - name: TIMEOUT_COMMIT
              value: 800ms
            - name: KEYS_CONFIG
              value: /configs/keys.json
            - name: METRICS
              value: 'false'
          command:
            - bash
            - '-c'
            - |-
              VAL_INDEX=${HOSTNAME##*-}
              echo "Validator Index: $VAL_INDEX"

              cp $CHAIN_DIR/cosmovisor/genesis/bin/$CHAIN_BIN /usr/bin

              echo "Running setup config script..."

              bash -e /scripts/update-config.sh
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - mountPath: /root/.persistenceCore
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
        - name: init-faucet
          image: ghcr.io/hyperweb-io/starship/faucet:20250325-2207109
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - '-c'
            - cp /bin/faucet /faucet/faucet && chmod +x /faucet/faucet
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - mountPath: /faucet
              name: faucet
      containers:
        - name: validator
          image: ghcr.io/cosmology-tech/starship/runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DENOM
              value: uxprt
            - name: COINS
              value: 100000000000000uxprt
            - name: CHAIN_BIN
              value: persistenceCore
            - name: CHAIN_DIR
              value: /root/.persistenceCore
            - name: CODE_REPO
              value: https://github.com/persistenceOne/persistenceCore
            - name: DAEMON_HOME
              value: /root/.persistenceCore
            - name: DAEMON_NAME
              value: persistenceCore
            - name: CHAIN_ID
              value: core-1
            - name: FAUCET_ENABLED
              value: 'true'
            - name: SLOGFILE
              value: slog.slog
            - name: DAEMON_NAME
              value: persistenceCore
            - name: DAEMON_HOME
              value: /root/.persistenceCore
          command:
            - bash
            - '-c'
            - |-
              #!/bin/bash
              set -euo pipefail

              START_ARGS=""


              /usr/bin/cosmovisor start $START_ARGS
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - mountPath: /root/.persistenceCore
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
          readinessProbe:
            exec:
              command:
                - bash
                - '-e'
                - /scripts/chain-rpc-ready.sh
                - http://localhost:26657
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
        - name: exposer
          image: ghcr.io/hyperweb-io/starship/exposer:20250205-544757d
          imagePullPolicy: IfNotPresent
          env:
            - name: GENESIS_HOST
              value: core-1-genesis
            - name: GENESIS_PORT
              value: '8081'
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EXPOSER_HTTP_PORT
              value: '8081'
            - name: EXPOSER_GRPC_PORT
              value: '9099'
            - name: EXPOSER_GENESIS_FILE
              value: /root/.persistenceCore/config/genesis.json
            - name: EXPOSER_MNEMONIC_FILE
              value: /configs/keys.json
            - name: EXPOSER_PRIV_VAL_FILE
              value: /root/.persistenceCore/config/priv_validator_key.json
            - name: EXPOSER_NODE_KEY_FILE
              value: /root/.persistenceCore/config/node_key.json
            - name: EXPOSER_NODE_ID_FILE
              value: /root/.persistenceCore/config/node_id.json
            - name: EXPOSER_PRIV_VAL_STATE_FILE
              value: /root/.persistenceCore/data/priv_validator_state.json
          command:
            - exposer
          resources:
            limits:
              cpu: '0.2'
              memory: 200M
            requests:
              cpu: '0.2'
              memory: 200M
          volumeMounts:
            - mountPath: /root/.persistenceCore
              name: node
            - mountPath: /configs
              name: addresses
        - name: faucet
          image: ghcr.io/cosmology-tech/starship/runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FAUCET_CONCURRENCY
              value: '5'
            - name: FAUCET_HTTP_PORT
              value: '8000'
            - name: FAUCET_CHAIN_BINARY
              value: persistenceCore
            - name: FAUCET_CHAIN_ID
              value: core-1
            - name: COINS
              value: 100000000000000uxprt
          command:
            - bash
            - '-c'
            - |-
              CREDIT_COINS=""
              FEES=""
              for coin in ${COINS//,/ }
              do
                  amt="${coin//[!0-9]/}"
                  denom="${coin//[0-9]/}"

                  # Calculate the order of magnitude
                  if [ ${#amt} -gt 18 ]; then
                    creditAmt=$(echo $amt | sed -e "s/000000$//")
                    feesAmt=$(echo $amt | sed -e "s/0000000000000$//")
                  else
                    creditAmt=$(echo $amt | sed -e "s/0000$//")
                    feesAmt=$(echo $amt | sed -e "s/00000000$//")
                  fi

                  if [[ $CREDIT_COINS == "" ]]
                  then
                    CREDIT_COINS="$creditAmt$denom"
                    FEES="$feesAmt$denom"
                  else
                    CREDIT_COINS="${CREDIT_COINS},$creditAmt$denom"
                  fi
              done

              export FAUCET_MNEMONIC=$(jq -r ".faucet[0].mnemonic" /configs/keys.json)

              export | grep "FAUCET"

              until bash -e /scripts/chain-rpc-ready.sh http://localhost:26657; do
                sleep 10
              done

              /faucet/faucet --credit-coins="$CREDIT_COINS" --chain-fees="$FEES"
          resources:
            limits:
              cpu: '0.1'
              memory: 128M
            requests:
              cpu: '0.1'
              memory: 128M
          volumeMounts:
            - mountPath: /configs
              name: addresses
            - mountPath: /faucet
              name: faucet
            - mountPath: /scripts
              name: scripts
          readinessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: node
          emptyDir: {}
        - name: addresses
          configMap:
            name: keys
        - name: scripts
          configMap:
            name: setup-scripts-core-1
        - name: faucet
          emptyDir: {}
