apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: starship
    starship.io/name: starship-e2e-tests-full-stack
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
spec:
  clusterIP: None
  ports: []
  selector:
    app.kubernetes.io/name: web-app
