apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  labels:
    app.kubernetes.io/instance: starship-generator-test
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: starship
data:
  1337.json: >-
    {"chain_name":"ethereum","assets":[{"base":"wei","name":"Ether","description":"The
    native token of
    Ethereum","display":"eth","symbol":"ETH","logo_URIs":{"png":"https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/eth-white.png","svg":"https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/eth-white.svg"},"denom_units":[{"denom":"wei","exponent":0},{"denom":"gwei","exponent":9},{"denom":"ether","exponent":18,"aliases":["ether"]}],"coingecko_id":"ethereum"}]}
