apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    starship.io/name: full-testnet
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: '8080'
  selector:
    app.kubernetes.io/name: explorer
