# Example values.yaml file will create 2 chains with 4 validators,
# a ts-relayer between them and the explorer
chains:
  - id: osmosis-1
    name: osmosis
    numValidators: 4
    ports:
      rest: 1313
      rpc: 26653
  - id: wasmd
    name: wasmd
    numValidators: 4
    ports:
      rpc: 26659
      rest: 1319

relayers:
  - name: osmo-wasm
    type: ts-relayer
    replicas: 1
    chains:
      - osmosis-1
      - wasmd

explorer:
  enabled: true

registry:
  enabled: true
