apiVersion: v1
kind: Service
metadata:
  name: ethereum-1337
  labels:
    starship.io/name: starship-generator-test
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: chain
    app.kubernetes.io/name: ethereum-1337
    app.kubernetes.io/part-of: '1337'
    app.kubernetes.io/role: service
    starship.io/chain-name: ethereum
    starship.io/chain-id: '1337'
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8545
      protocol: TCP
      targetPort: '8545'
    - name: ws
      port: 8546
      protocol: TCP
      targetPort: '8546'
    - name: rpc
      port: 8551
      protocol: TCP
      targetPort: '8551'
  selector:
    app.kubernetes.io/name: ethereum-1337
