apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: registry-config
data:
  custom-1.json: '{"chain_name":"custom","assets":[]}'
