apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer
  labels:
    app.kubernetes.io/instance: complex-testnet
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
data:
  osmosis-build.json: >-
    {"chain_name":"osmosis-build","coingecko":"osmosis","api":"http://osmosis-build-genesis.$(NAMESPACE).svc.cluster.local:1313","rpc":["http://osmosis-build-genesis.$(NAMESPACE).svc.cluster.local:26653"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":118,"min_tx_fee":"3000","addr_prefix":"osmo","logo":"","assets":[{"base":"uosmo","symbol":"OSMO","exponent":"6","coingecko_id":"osmosis-build","logo":""}]}
  osmosis-cosmjs.json: >-
    {"chain_name":"osmosis-cosmjs","coingecko":"osmosis","api":"http://osmosis-cosmjs-genesis.$(NAMESPACE).svc.cluster.local:1313","rpc":["http://osmosis-cosmjs-genesis.$(NAMESPACE).svc.cluster.local:26653"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":118,"min_tx_fee":"3000","addr_prefix":"osmo","logo":"","assets":[{"base":"uosmo","symbol":"OSMO","exponent":"6","coingecko_id":"osmosis-cosmjs","logo":""}]}
  ethereum-1.json: >-
    {"chain_name":"ethereum-1","coingecko":"ethereum","api":"http://ethereum-1-genesis.$(NAMESPACE).svc.cluster.local:1317","rpc":["http://ethereum-1-genesis.$(NAMESPACE).svc.cluster.local:26657"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":60,"min_tx_fee":"3000","addr_prefix":"eth","logo":"","assets":[{"base":"wei","symbol":"ETH","exponent":"6","coingecko_id":"ethereum-1","logo":""}]}
