apiVersion: v1
kind: Service
metadata:
  name: osmosis-1-cometmock
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: chain
    app.kubernetes.io/name: osmosis-1-cometmock
    app.kubernetes.io/type: osmosis-1-service
    app.kubernetes.io/role: cometmock
    starship.io/chain-name: osmosis
    starship.io/chain-id: osmosis-1
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 22331
      protocol: TCP
      targetPort: 22331
  selector:
    app.kubernetes.io/name: osmosis-1-cometmock
