apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app.kubernetes.io/instance: special-testnet
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: starship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        app.kubernetes.io/instance: special-testnet
        app.kubernetes.io/version: 4.0.0-alpha.0
        app.kubernetes.io/managed-by: starship
    spec:
      containers:
        - name: registry
          image: ghcr.io/cosmology-tech/starship/registry:latest
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9090
          env:
            - name: REGISTRY_CHAIN_CLIENT_RPCS
              value: http://test-chain-1-genesis.$(NAMESPACE).svc.cluster.local:26657
            - name: REGISTRY_CHAIN_API_RPCS
              value: http://test-chain-1-genesis.$(NAMESPACE).svc.cluster.local:26657
            - name: REGISTRY_CHAIN_API_GRPCS
              value: http://test-chain-1-genesis.$(NAMESPACE).svc.cluster.local:9091
            - name: REGISTRY_CHAIN_API_RESTS
              value: http://test-chain-1-genesis.$(NAMESPACE).svc.cluster.local:1317
            - name: REGISTRY_CHAIN_CLIENT_EXPOSERS
              value: http://test-chain-1-genesis.$(NAMESPACE).svc.cluster.local:8081
          volumeMounts:
            - name: chain-test-chain-1
              mountPath: /chains/test-chain-1
          resources:
            limits:
              cpu: '0.1'
              memory: 128M
            requests:
              cpu: '0.1'
              memory: 128M
          readinessProbe:
            httpGet:
              path: /health
              port: '8080'
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: '8080'
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: chain-test-chain-1
          configMap:
            name: chain-test-chain-1
