apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    starship.io/name: full-testnet
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        starship.io/name: full-testnet
        app.kubernetes.io/version: 4.0.0-alpha.0
        app.kubernetes.io/managed-by: starship
    spec:
      containers:
        - name: registry
          image: registry:latest
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9090
          env:
            - name: REGISTRY_CHAIN_CLIENT_RPCS
              value: http://localhost:26653
            - name: REGISTRY_CHAIN_API_RPCS
              value: http://localhost:26653
            - name: REGISTRY_CHAIN_API_GRPCS
              value: http://osmosis-1-genesis.$(NAMESPACE).svc.cluster.local:9091
            - name: REGISTRY_CHAIN_API_RESTS
              value: http://localhost:1313
            - name: REGISTRY_CHAIN_CLIENT_EXPOSERS
              value: http://osmosis-1-genesis.$(NAMESPACE).svc.cluster.local:8081
          volumeMounts:
            - name: chain-osmosis-1
              mountPath: /chains/osmosis-1
          resources:
            limits:
              cpu: '0.2'
              memory: 200M
            requests:
              cpu: '0.2'
              memory: 200M
          readinessProbe:
            httpGet:
              path: /health
              port: '8080'
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: '8080'
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: chain-osmosis-1
          configMap:
            name: chain-osmosis-1
