apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer
  labels:
    starship.io/name: starship-ingress-test
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/name: explorer
data:
  osmosis-1.json: >-
    {"chain_name":"osmosis-1","coingecko":"osmosis","api":"https://rest.osmosis-1-genesis.example.com:443","rpc":["https://rpc.osmosis-1-genesis.example.com:443"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":118,"min_tx_fee":"3000","addr_prefix":"osmo","logo":"","assets":[{"base":"uosmo","symbol":"OSMO","exponent":"6","coingecko_id":"osmosis-1","logo":""}]}
