{{- range $chain := .Values.chains }}
{{- if and (eq $chain.type "solana") $chain.bench.enabled }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}
{{ $chain := include "devnet.fullchain" (dict "name" $chain.id "file" $defaultFile "context" $) | fromJson }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $chain.hostname }}-bench"
spec:
  template:
    spec:
      containers:
      - name: bench
        image: {{ $chain.image }}
        command: ["/bin/bash", "-c"]
        args:
          - /scripts/bench-tps.sh
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: setup-scripts-{{ $chain.hostname }}
          defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
{{- end }} 