{{- range $chain := .Values.chains }}
{{- if (eq $chain.name "solana") }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}

{{ $chain := include "devnet.fullchain" (dict "name" $chain.id "file" $defaultFile "context" $) | fromJson }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chain.hostname }}-genesis
  labels:
    app.kubernetes.io/name: {{ $chain.id }}-genesis
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 8899
      protocol: TCP
      targetPort: 8899
    - name: ws
      port: 8900
      protocol: TCP
      targetPort: 8900
    - name: p2p
      port: 8001
      protocol: TCP
      targetPort: 8001
    {{- if $chain.metrics }}
    - name: metrics
      port: 26660
      protocol: TCP
      targetPort: 26660
    {{- end }}
    - name: exposer
      port: {{ $.Values.exposer.ports.rest | default 8081 }}
      protocol: TCP
      targetPort: {{ $.Values.exposer.ports.rest | default 8081 }}
    - name: faucet
      port: 9900
      protocol: TCP
      targetPort: 9900
  selector:
    app.kubernetes.io/name: {{ $chain.id }}-genesis
---
{{- if gt $chain.numValidators 1.0}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devnet.chain.name" $chain.id }}-validator
  labels:
    app.kubernetes.io/name: {{ $chain.id }}-validator
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 8899
      protocol: TCP
      targetPort: 8899
    {{- if $chain.metrics }}
    - name: metrics
      port: 26660
      protocol: TCP
      targetPort: 26660
    {{- end }}
    - name: exposer
      port: {{ $.Values.exposer.ports.rest | default 8081 }}
      protocol: TCP
      targetPort: {{ $.Values.exposer.ports.rest | default 8081 }}
  selector:
    app.kubernetes.io/name: {{ $chain.id }}-validator
---
{{- end }}
{{- end }}
{{- end }}