apiVersion: v1
kind: Service
metadata:
  name: neutron-query-relayer-nqr-neutron-cosmos
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: relayer
    app.kubernetes.io/part-of: starship
    app.kubernetes.io/role: neutron-query-relayer
    app.kubernetes.io/name: neutron-query-relayer-nqr-neutron-cosmos
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: neutron-query-relayer-nqr-neutron-cosmos
