apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: starship
    starship.io/name: starship-ingress-test
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
spec:
  clusterIP: None
  ports: []
  selector:
    app.kubernetes.io/name: my-app
