apiVersion: v1
kind: Service
metadata:
  name: simapp-genesis
  labels:
    starship.io/name: starship-e2e-tests
    app.kubernetes.io/version: 4.0.0-alpha.1
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: chain
    app.kubernetes.io/name: simapp-genesis
    app.kubernetes.io/type: simapp-service
    app.kubernetes.io/role: genesis
    starship.io/chain-name: simapp
    starship.io/chain-id: simapp
spec:
  clusterIP: None
  ports:
    - name: p2p
      port: 26656
      protocol: TCP
      targetPort: '26656'
    - name: address
      port: 26658
      protocol: TCP
      targetPort: '26658'
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: '9090'
    - name: grpc-web
      port: 9091
      protocol: TCP
      targetPort: '9091'
    - name: rest
      port: 1317
      protocol: TCP
      targetPort: '1317'
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: '26657'
    - name: metrics
      port: 26660
      protocol: TCP
      targetPort: '26660'
    - name: exposer
      port: 8081
      protocol: TCP
      targetPort: '8081'
    - name: faucet
      port: 8000
      protocol: TCP
      targetPort: '8000'
  selector:
    app.kubernetes.io/name: simapp-genesis
