apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer
  labels:
    starship.io/name: starship-generator-test
    app.kubernetes.io/version: 4.0.0-alpha.0
    app.kubernetes.io/managed-by: starship
    app.kubernetes.io/component: explorer
    app.kubernetes.io/part-of: starship
data:
  core-1.json: >-
    {"chain_name":"core-1","coingecko":"persistencecore","api":"http://core-1-genesis.$(NAMESPACE).svc.cluster.local:1318","rpc":["http://core-1-genesis.$(NAMESPACE).svc.cluster.local:26658"],"snapshot_provider":"","sdk_version":"0.45.6","coin_type":118,"min_tx_fee":"3000","addr_prefix":"persistence","logo":"","assets":[{"base":"uxprt","symbol":"PERSISTENCE","exponent":"6","coingecko_id":"core-1","logo":""}]}
