name: Lint and Test Charts

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "starship/charts/**"
      - ".github/workflows/lint-check.yaml"
  pull_request:
    branches:
      - main
      - v1
    paths:
      - "starship/charts/**"
      - ".github/workflows/lint-check.yaml"
    types: [ opened, reopened, synchronize, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  lint-test:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starship/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs charts --charts charts/devnet
